Structural construction
cr-crme/banque_stages pull request #3
Opened 2022-10-03 15:31 UTC by QuentinGast

Added homepage and risk cards page. Added links between those pages Added base structure of these pages:

Homepage has 2 clickable widgets, one with a searchbar (non-functioning)
Risks page has a list of risks pulled from a hardcoded json string

Added subsequent risk class

2022-10-18 15:48 UTC, BlackbirdShadow commented
Ajouté le travail du dernier sprint. Dans le futur, il y aura des merge sur le pull request plus souvent qu'une fois par sprint.

2022-10-21 14:39 UTC, pariterre requested changes
Good, please, make sure any communication is done in english, as it is the coding language :)

> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cr-crme/banque_stages/3#-:-NEulbrsEsPm6wO0RBQ5:b-2s9ikd)* status: all files reviewed, 26 unresolved discussions (waiting on @QuentinGast)

___
*[`lib/common/widgets/main_drawer.dart` line 2 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/3#-NEuly3S9Od3MgME-xGD:-NEuly3S9Od3MgME-xGE:b-c32xou) ([raw file](https://github.com/cr-crme/banque_stages/blob/992a68ed19ac01ec45a6368da2591378eb63b2d9/lib/common/widgets/main_drawer.dart#L2)):*
> ```Dart
> import 'package:crcrme_banque_stages/screens/home_screen.dart';
> import 'package:crcrme_banque_stages/screens/ref_sst/home_sst/home_sst_screen.dart';
> ```

I'll write it only once, but it applies everywhere. To avoid risks of collision with installed version, local packages should not be imported using `package:xxx` nomenclature, but `./...`, even though the automatic importer of VScode does like this. Also, since they are local packages, they should appear after the `'package:xxx` section separated by a white space
Ideally in alphabetical order
___
*[`lib/common/widgets/main_drawer.dart` line 50 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/3#-NEumkb83oN7BzXXKyTh:-NEumkb83oN7BzXXKyTi:bzw78r) ([raw file](https://github.com/cr-crme/banque_stages/blob/992a68ed19ac01ec45a6368da2591378eb63b2d9/lib/common/widgets/main_drawer.dart#L50)):*
> ```Dart
>                   titleText: "Référentiel SST",
>                   icon: Icon(Icons.warning_rounded),
>                   route: HomeSSTScreen.route,
> ```

I have the habbit of calling it `routeName`
___
*[`lib/screens/ref_sst/sst_cache.dart` line 27 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/3#-NEun9hU8pFH5KJqwQbI:-NEun9hU8pFH5KJqwQbJ:blj8d2m) ([raw file](https://github.com/cr-crme/banque_stages/blob/992a68ed19ac01ec45a6368da2591378eb63b2d9/lib/screens/ref_sst/sst_cache.dart#L27)):*
> ```Dart
>   List<RiskSST> getRisks() {
>     return risks;
>   }
> ```

The vanilla way in dart is to actually declare the parameters public but to declare the class const class. Then to provide a `copyWith` method so one can create a new class with some modified parameters at low cost



_Code quote:_
```Dart
  List<JobSST> getJobs() {
    return jobs;
  }

  List<RiskSST> getRisks() {
    return risks;
  }
```
___
*[`lib/screens/ref_sst/sst_cache.dart` line 30 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/3#-NEuo3b61Lx9L2Y5LWn0:-NEuo3b61Lx9L2Y5LWn1:bgnabnq) ([raw file](https://github.com/cr-crme/banque_stages/blob/992a68ed19ac01ec45a6368da2591378eb63b2d9/lib/screens/ref_sst/sst_cache.dart#L30)):*
> ```Dart
> 
>   ListView getListViewJob() {
>     return ListView(
> ```

I don't think it makes sense to introduce a dependency to flutter in the class. If one needs a list view of a list, they can do it on the fly. Also, please do use ListViewBuilder and not ListView for unknown sized Arrays



_Code quote:_
```Dart
  ListView getListViewJob() {
    return ListView(
        children: [for (JobSST job in jobs) SSTCard(job.jobCode, job.jobName)]);
  }
```
___
*[`lib/screens/ref_sst/sst_cache.dart` line 40 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/3#-NEuoTFJ83dVncvri3Ij:-NEuoTFJ83dVncvri3Ik:bj9xvrc) ([raw file](https://github.com/cr-crme/banque_stages/blob/992a68ed19ac01ec45a6368da2591378eb63b2d9/lib/screens/ref_sst/sst_cache.dart#L40)):*
> ```Dart
>   }
> 
>   void refresh() {
> ```

Typically, this is the copyWith method I was refering to before. 
What you did works, but there are vanilla ways to do that using ListViewBuilder that makes this class actually useless (You are recoding what the `Builder` part of `ListView` is for)



_Code quote:_
```Dart
  void refresh() {
    jobs = ProxySST().getJobList();
    risks = ProxySST().getRiskList();
  }
```
___
*[`lib/screens/ref_sst/common/dummy_sst_risks.json` line 8 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/3#-NEuosPwC1iN6Kw6HeGx:-NEuosPwC1iN6Kw6HeGy:b-rqy7ls) ([raw file](https://github.com/cr-crme/banque_stages/blob/992a68ed19ac01ec45a6368da2591378eb63b2d9/lib/screens/ref_sst/common/dummy_sst_risks.json#L8)):*
> ```JSON
>             "name": "Risques Chimiques",
>             "description" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
>             "image" : "iVBORw0KGgoAAAANSUhEUgAAAfQAAAH0CAIAAABEtEjdAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAABUnSURBVHhe7d2/XeNOAsbhjYnINnFCdAWQ0cD2QAFk1HAtbDU0QzF3tjH2jKTRP4NgX575PMHdIhlp9uevBtmLf/3vv/8BIIy4AwQSd4BA4g4QSNwBAok7QCBxBwgk7gCBxB0gkLgDBBJ3gEDiDhBI3AECiTtAIHEHCCTuAIHEHSCQuAMEEneAQOIOEEjcAQKJO0AgcQcIJO4AgcQdIJC4AwQSd4BA4g4QSNwBAok7QCBxBwgk7gCBxB0gkLgDBBJ3gEDiDhBI3AECiTtAIHEHCCTuAIHEHSCQuAMEEneAQOIOEEjcAQKJO0AgcQcIJO4AgcQdIJC4AwQSd4BA4g4QSNwBAok7QCBxBwgk7gCBxB0gkLgDBBJ3gEDiDhBI3AECiTtAIHEHCCTuAIHEHSCQuAMEEneAQOIOEEjcAQKJO0AgcQcIJO4AgcQdIJC4AwQSd4BA4g4QSNwBAok7QCBxBwgk7gCBxB0gkLgDBBJ3gEDiDhBI3AECiTtAIHEHCCTuAIHEHSCQuAMEEneAQOIOEEjcAQKJO0AgcQcIJO4AgcQdIJC4AwQSd4BA4g4QSNwBAok7QCBxBwgk7gCBxB0gkLgDBBJ3gEDiDhBI3AECiTtAIHEHCCTuAIHEHSCQuAMEEneAQOIOEEjcAQKJO0AgcQcIJO4AgcQdIJC4AwQSd4BA4g4QSNwBAok7QCBxBwgk7gCBxB0gkLgDBBJ3gEDiDhBI3AECiTtAIHEHCCTuAIHEHSCQuAMEEneAQOIOEEjcAQKJO0AgcQcIJO4AgcQdIJC4AwQSd4BA4g4QSNwBAok7QCBxBwgk7gCBxB0gkLgDBBJ3gEDiDhBI3AECiTtAIHEHCCTuAIHEHSCQuAMEEneAQOIOEEjcAQKJO0AgcQcIJO7bebn/9T5uXy5/fvd3d/rT93Hz9/n81bPd0+mr51E+SM/j7Wmr43h67G3QdPfy5/Zhd3Pa8zBuHu5/vzzf9bZ80z+w5nj403oQ4IOJ+3Zmx32oxc+/H05fPI+xuBff6zBmVvV1n/XTHkNj9/u1t4u4w/ck7tuZH/eBCNYr8eMYiXsvuMNdrrzcl6v1xtj1v6m4w3ck7tuZH/d+izsr8eNox33gSjB4q+fi9c+Msr+N+129r7jDdyTu25mO++7m/a5IJ9xDF4B23IeuBONh7QT65unP7nx1eX3s3BHqXCeKfWf8fABsQ9y3MyPut0+n/90K6M3DpfKtuJelPl8txspbL9tvX6Zezq2vE+IO35G4b2dG3H//fd+mCuj51dRig2bcy3sy97vim7buzFThbr6vpnzYKuLiDt+RuG9nTtxfzovo8tb2OaxVrIfjXmxwLHUR5eE7M81qd+wjfnhP5N/Hu3obcYfvSNy3Myfur8Ui/RzK822TfZ2n4l4uw48blO+hHIpveU9m9L58i7jDdyTu25kV90srz9tcNtivxCfiXt+TOf5h8fhDd2a6K/36qzOUl5PR0X2bDfCJxH078+Jepfy4wbmehzSPx32w1KNr84n0zyDu8B2J+3bmxf2y2SnEl/sqh71G4152tvjqwHL+bDzuzXAXa3xxh+9I3LczM+7ly6eHDc7/t07/QNybEW9E/0DcIZO4b2du3OvXVC83VY5xHIl78aXu7ZfyS/WN9TLunS/tLYz72/ED34C4b2du3C+5rG6yv/W0HfeVK+h29/fEHf5V4r6d2XG//MnT4/l/n+6ZNONevuVxYlQ7Vv88dfTOSbmluMM3J+7bmR33y5YP9+ffwXvapRX3qtFTo1qhl3fqOxeMmrjDP0TctzM/7nVwj6PX/eaDzBnNl1vH/h2TuMM/RNy3syDu/Xss7zkefpCpf4Z6UD1mtUKvV/2Nd7vXhyTu8M2J+3YWxL1eTe/HeUE9+CBlndtL72p1X92Z6X67+lf+Pu/+9j7HQ9zhmxP37SyJe/c2yzmmQw9SbtxYdx9VK/TOa6f9G0Fjo/wu3evQ2FB/2Iq4b2dJ3MuN9+MS04EHad9v6Rp97bS+OdMeu84vfBd3+I7EfTuL4t4Kcf9BxtbjXWWIB9b4r4+jH5Bd3655J+7wHYn7dpbFvVyPF8nuPUh1A6e+kz6g2L11d/7u9fH30+UD//bj5mF32/s17mfiDt+RuAMEEneAQOIOEEjcAQKJO0AgcQcIJO4AgcQdIJC4AwQSd4BA4g4QSNwBAok7QCBxBwgk7gCBxB0gkLhvZvxDLW4edoOfc1R+Fkf5ER9L1J+POvmBHoW7lz+3D8WHgRwO8iM+taP4nJDGZ5VU5k3Cc/dof71NafNDZVfMbfXRKL3xYZ9qMjw/jbH/S3m4/11/9iGI+3bmPbd3ncqsCFBX+elL+9H4AKau130oT3v0x+DHcH9h3O9e7sc+APbhvn/V3Fsxt9OpPYzux8y++ay4v4/9dff8vUDctzP7uV01bkWAOnrfd8Zn3Y238jj6KfmyuHeuXsNj4MFXzO381PYf8LPjvh+DF11+KHHfzILndtHNFQGq1fdkjmMiAdUnbo+NzvF8TdxnH23/08NXzO2S1HZPZ4O4T35COj+IuG+meG53nvaHm8V1oS5P0RUBqgyuaot29HUadPP38RKazoq+fpz2CY4pTnBF3MuPET+M6iWB18fOVzuvN6yY25Gjfftg8dMX30b97T5nfp53xVnsx5r/SIgk7puZeG7XK9DzU3RFgEplqW8upWvHpXEYczb4grjXl64ZrwRU32LF3E4ebfmYnXX0581P9bfszgxvxH0zk8/t8il6bs2KABXKezL3uyKFrQRUKWy8QFf1q9jm8+LVmoQ5R9tZ3ZcnvmJuZxxt9e0aR/uJ89OeB34Ycd/M5HO7TNXHxL1c2B6e80Xrh+/MlGFqB+iweD++y7B+T8jmcS8vXaPfsZyHxu3sj4t79bDbX/zEnRNx38zUc3t4xbciQGe9q8VUu8tbLqP35QdtHffqBtHoC4mNLVfM7ZyjbV1LPm9+yr9ot2U4EffNTDy3qwBdNlgRoHf1PZnjH5aPNlCB8hiWLwDLxIyOKsTlIc0Zl0no/lxyecye4TX+irmdk9rWNfLq+Rn8z+Z5V72K2z4qfhpx30w77p/zbpnB9jW6c7IglwM2jnu148TRDv/IsmJuJ1J7MnBZ3dtifpb/rRFL3Dcz+7l97Yt+b8pvV+w43J2TfzbuU/ciPuyWV7HL94v7Q+8vlJ9M3Ddz/XN7SdybEW9E/0jcpxS7fK+4H97gX+wF4r6dec/tbjJWBOigzHTn9stIwT8s7iPh65qTy8FJqKo3c [...]

2022-10-28 20:43 UTC, BlackbirdShadow commented
Update on PR:
- Implemented corrections from @pariterre 's reviews concerning proxies, and risk, list, job classes. Remaining corrections will wait for the next meeting (we have questions)
- New risk structure (now 3 different class: card, risk, links)
- Risk JSON has been updated to reflect new risk structure
- Risk JSON noew generated automatically with python script from excel file
- Proxies have been updated to reflect new risk structure
- Unitary tests updated to reflect new risk structure

2022-10-31 13:53 UTC, mapleduck commented
Added UI changes:
The list risks page and the card page have a UI. It is now needed to connect the UI to the proxy.

2022-10-31 15:10 UTC, pariterre requested changes
> Reviewed 18 of 19 files at r2, 1 of 1 files at r3, 5 of 10 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cr-crme/banque_stages/3)* status: all files reviewed, 23 unresolved discussions (waiting on @QuentinGast)

___
*[`pubspec.yaml` line 54 at r5](https://reviewable.io/reviews/cr-crme/banque_stages/3#-NFi_mZmATna6E8AiOGH:-NFi_mZmATna6E8AiOGI:b-n7osgu) ([raw file](https://github.com/cr-crme/banque_stages/blob/0b72737c2a60d926f9548613a07a6daa3c27b888/pubspec.yaml#L54)):*
> ```YAML
>     assets:
>         - assets/jobs-data.json
>         - assets/1.png
> ```

Do not include image in the repo
___
*[`assets/1.png` line 0 at r5](https://reviewable.io/reviews/cr-crme/banque_stages/3#-NFi_gsv9PDc7gWwKO5x:-NFi_gsv9PDc7gWwKO5y:bm8evxg) ([raw file](https://github.com/cr-crme/banque_stages/blob/0b72737c2a60d926f9548613a07a6daa3c27b888/assets/1.png#L0)):*
AGAIN... Do NOT include image in the repo...
___
*[`lib/screens/ref_sst/common/proxy_ref_sst.dart` line 1 at r3](https://reviewable.io/reviews/cr-crme/banque_stages/3#-NFi9M9eBz0M-CWZJe__:-NFi9M9eBz0M-CWZJe_a:brxg17i) ([raw file](https://github.com/cr-crme/banque_stages/blob/105984b1957f387725f3e84b25a6c223b9009d6b/lib/screens/ref_sst/common/proxy_ref_sst.dart#L1)):*
> ```Dart
> // ignore_for_file: non_constant_identifier_names, prefer_interpolation_to_compose_strings
> ```

Do not ignore warnings, fix them! I just noticed this is everywhere, please remove all these "ignores"
___
*[`lib/screens/ref_sst/common/proxy_ref_sst.dart` line 117 at r3](https://reviewable.io/reviews/cr-crme/banque_stages/3#-NFiW3449P34Oz3dho1B:-NFiW3449P34Oz3dho1C:bzfqfvs) ([raw file](https://github.com/cr-crme/banque_stages/blob/105984b1957f387725f3e84b25a6c223b9009d6b/lib/screens/ref_sst/common/proxy_ref_sst.dart#L117)):*
> ```Dart
>   }
> 
>   List<CardSST> getList() {
> ```

I do not understand the gol of this list (of saving the parsedRisks instead of the actual List<CardSST>)



_Code quote:_
```Dart
  List<CardSST> getList() {
    return fromJson(parsedRisks);

  }
```
___
*[`lib/screens/ref_sst/risks_cards/risks_cards_screen.dart` line 9 at r5](https://reviewable.io/reviews/cr-crme/banque_stages/3#-NFiWTtA7qFwh6U2jo3p:-NFiWTtA7qFwh6U2jo3q:b-kc80x8) ([raw file](https://github.com/cr-crme/banque_stages/blob/0b72737c2a60d926f9548613a07a6daa3c27b888/lib/screens/ref_sst/risks_cards/risks_cards_screen.dart#L9)):*
> ```Dart
> import 'package:crcrme_banque_stages/screens/ref_sst/risks_cards/widgets/sub_title.dart';
> import 'package:crcrme_banque_stages/screens/ref_sst/risks_cards/widgets/situation_risk.dart';
> import 'package:crcrme_banque_stages/screens/ref_sst/risks_cards/widgets/factors.dart';
> ```

Do not refer to local packages as `'package:crcme_banque_stages/...'`



_Code quote:_
```Dart
import 'package:crcrme_banque_stages/screens/ref_sst/common/card_sst.dart';
import 'package:crcrme_banque_stages/screens/ref_sst/risks_cards/widgets/introduction.dart';
import 'package:crcrme_banque_stages/screens/ref_sst/risks_cards/widgets/link.dart';
import 'package:crcrme_banque_stages/screens/ref_sst/risks_cards/widgets/main_title.dart';
import 'package:crcrme_banque_stages/screens/ref_sst/risks_cards/widgets/sub_title.dart';
import 'package:crcrme_banque_stages/screens/ref_sst/risks_cards/widgets/situation_risk.dart';
import 'package:crcrme_banque_stages/screens/ref_sst/risks_cards/widgets/factors.dart';
import 'package:crcrme_banque_stages/screens/ref_sst/risks_cards/widgets/symptoms.dart';
```
___
*[`lib/screens/ref_sst/risks_cards/risks_cards_screen.dart` line 76 at r5](https://reviewable.io/reviews/cr-crme/banque_stages/3#-NFiYczg64uoaS6TU8Db:-NFiYczg64uoaS6TU8Dc:b-f0a1iu) ([raw file](https://github.com/cr-crme/banque_stages/blob/0b72737c2a60d926f9548613a07a6daa3c27b888/lib/screens/ref_sst/risks_cards/risks_cards_screen.dart#L76)):*
> ```Dart
>             SubTitle(index, subTitle),
>             Introduction(intro),
>             Image.asset('assets/1.png'), //Testing how the picture is display
> ```

Again, please do not push images... fetch them from the internet if really needed
___
*[`test/job_proxy_test.mocks.dart` line 17 at r3](https://reviewable.io/reviews/cr-crme/banque_stages/3#-NFiZWETBzrrOprZJQy3:-NFiZWETBzrrOprZJQy4:b-mpt20t) ([raw file](https://github.com/cr-crme/banque_stages/blob/105984b1957f387725f3e84b25a6c223b9009d6b/test/job_proxy_test.mocks.dart#L17)):*
> ```Dart
> // ignore_for_file: comment_references
> // ignore_for_file: implementation_imports
> // ignore_for_file: invalid_use_of_visible_for_testing_member
> ```

make sure these are absolutely necessary. If so, make them per_line if possible



_Code quote:_
```Dart
// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
```


<!-- Sent from Reviewable.io -->

2022-12-14 18:32 UTC, BlackbirdShadow commented
Updated fork from remote

2023-03-06 14:28 UTC, merged